name: attendance_camera_app
description: "Face Recognition Camera Module for Attendance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
